# Generated by Django 5.0.3 on 2024-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
